### ISSUE TITLE
Doesn't tag screenshots

### ISSUE THREAD

**Issue by suparng-medallia** [onesky/auto-screenshot-ios#8]
I am able to upload screenshots but it doesn't tag them with localizable strings.

**Comment by bretdabaker** [comment]
I have checked your project and it only contains an `en.xliff` file, please note that our screenshot SDK only supports `.strings` file at the moment. Since there are orders in progress, once the translations come back, you can try the following steps to switch back to using `.strings`:

1. export the source and translations as `.xliff` files.
2. import them into your Xcode project so that it generates the `.strings` files for you.
3. create a new project on OneSky.
4. upload the `.strings` files to the project manually or via our [Xcode IDE plugin](https://github.com/onesky/plugin-xcode).
5. upload screenshots to the new project using the screenshot SDK.
